# vim: set ft=yaml sw=2:
stages:
  - build
  - run
  - test
  - push
  - npins

variables:
  NIX_PATH: "nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixpkgs"
  COMMIT_LOG: "1"
  CI_COMMIT_MESSAGE: "Overwritten, because https://stackoverflow.com/questions/28865473/setting-environment-variable-to-a-large-value-argument-list-too-long#28865503"
  CI_COMMIT_DESCRIPTION: "see above"

build:
  stage: build
  script:
    - ./ci/build
  artifacts:
    paths:
      - ./wp4nix

run_full:
  stage: run
  only:
    - schedules
  artifacts:
    paths:
      - ./*.log
      - ./*.json
  script:
    - ./ci/run

run_debug:
  stage: run
  except:
    - schedules
  variables:
    DEBUG: "1"
  artifacts:
    paths:
      - ./*.log
      - ./*.json
  script:
    - ./ci/run

test:
  stage: test
  interruptible: true
  script:
    - ./ci/test

push:
  stage: push
  only:
    - schedules
  script:
    - ./ci/push

helsinki_npins:
  stage: npins
  trigger:
    project: helsinki-systems/helsinki
    branch: feat/initial-npins-support
  variables:
    COMMAND: update_pin
    PIN: wp4nix
