# vim: set ft=yaml sw=2:
stages:
  - compliance
  - lint
  - build
  - run
  - test
  - push
  - npins

include:
  - project: "helsinki-systems/gitlab-ci-templates"
    ref: "master"
    file:
      # TODO: Use go/all.yml
      - "common.yml"

default:
  tags:
    - nix
    - helsinki-hydra-builder02

variables:
  NIX_PATH: "nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixpkgs"
  COMMIT_LOG: "1"
  CI_COMMIT_MESSAGE: "Overwritten, because https://stackoverflow.com/questions/28865473/setting-environment-variable-to-a-large-value-argument-list-too-long#28865503"
  CI_COMMIT_DESCRIPTION: "see above"

build:
  stage: build
  needs: []
  when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $COMMAND == "renovate"'
      when: never
    - when: always
  script:
    - ./ci/build
  artifacts:
    paths:
      - ./wp4nix

run_full:
  stage: run
  needs:
    - build
  when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $COMMAND == "run"'
  artifacts:
    paths:
      - ./*.log
      - ./*.json
  script:
    - ./ci/run
    - ./ci/test

run_debug:
  stage: run
  needs:
    - build
  when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  variables:
    DEBUG: "1"
  artifacts:
    paths:
      - ./*.log
      - ./*.json
  script:
    - ./ci/run
    - ./ci/test

test:
  stage: test
  needs: []
  when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $COMMAND == "renovate"'
      when: never
    - when: always
  script:
    - ./ci/test

push:
  stage: push
  needs:
    - run_full
  when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $COMMAND == "run"'
  script:
    - ./ci/push

helsinki_npins:
  stage: npins
  needs:
    - push
  when: always
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $COMMAND == "run"'
  trigger: helsinki-systems/helsinki
  variables:
    COMMAND: update_pin
    PIN: wp4nix
